### ISSUE TITLE
https://github.com/TechnoAndy/Kanban-Board

### ISSUE THREAD

**Issue by TechnoAndy** [TechnoAndy/space-travelers-hub#18]
We are 2 people in our group for this project.

https://github.com/TechnoAndy/Kanban-Board/projects/1

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi @TechnoAndy and @AbayomiOlaoye,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=In%20its%20description%2C%20paste%20a%20link%20to%20your%20GitHub%20project.), Please add the link to your GitHub project here in the Issue description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @TechnoAndy and @AbayomiOlaoye,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Changes Required) Aspects to improve: ♻️

- [x] Please assign all group tasks to both of you or at least one of you regarding the equal amount of work shared rule.

![image](https://user-images.githubusercontent.com/68796232/204306550-5035ecf0-8254-47ae-8cb9-3dcd78b4dc37.png)


## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] [REQUIRED] Good job so far!  You should have sent you a link to the `GitHub issue` that has a link to the `GitHub project` not a `Githun repo` link but you paste the link on your issue's description your [Github Repository](https://github.com/TechnoAndy/Kanban-Board) link, change it to [this link](https://github.com/TechnoAndy/Kanban-Board/projects/1) 🙏 

![image](https://user-images.githubusercontent.com/63915024/204310101-d557aee7-5ca3-471c-935c-3e081bdb028a.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Nemwel-Boniface** [comment]
## Hello team      :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
